version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  node: circleci/node@4.0.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: './BackEnd/project'
          test_results_path: './BackEnd/project/target/surefire-reports'
  react_test:
    jobs:
      - node/test:
          app-dir: './FrontEnd/agme-booking'